podcast:
  subject: "MotoGP"
  podcaster: "Cody"
rss:
  url: "https://flipboard.com/topic/motogp.rss"
  max_articles: 10
ollama:
  end_point: "http://localhost:11434/api/generate"
  model: "codeup:13b"