rss:
  url: https://news.google.com/rss/search?q=australia
  max_articles: 10
  filters:
  - Daily
  - Weekly
ollama:
  end_point: http://localhost:11434/api/generate
  model: mistral:7b
podcast:
  subject: News
  podcaster: Cody
tts:
  engine: mlx
  coqui:
    url: http://localhost:5002/api/tts
  kokoro:
    url: http://localhost:8880
    voice: bm_george
    speed: 1
    format: mp3
  mlx:
    url: http://localhost:8000
    voice: bm_george
    speed: 1.2
    format: mp3
