podcast:
  subject: "News"
  podcaster: "Cody"
rss:
  url: "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best"
  max_articles: 10
  filters:
    - "Daily"
    - "Weekly"
ollama:
  end_point: "http://localhost:11434/api/generate"
  model: "mistral:7b"
tts:
  url: "http://localhost:5002/api/tts"