podcast:
  subject: "News"
  podcaster: "Cody"
rss:
  url: "https://news.google.com/rss/search?q=australia"
  max_articles: 15
  filters:
    - "Daily"
    - "Weekly"
ollama:
  end_point: "http://localhost:11434/api/generate"
  model: "gemma3:1b"
tts:
  engine: "kokoro"  # Options: "coqui" or "kokoro"
  coqui:
    url: "http://localhost:5002/api/tts"
  kokoro:
    url: "http://localhost:8880"
    voice: "bm_george"  # Default voice, options: af_heart, en_heart, etc.
    speed: 1.0  # Range: 0.25 to 4.0
    format: "mp3"  # Options: mp3, opus, flac, wav, pcm